import Head from 'next/head'
import Image from 'next/image'
import { Container, Navbar,Row,Col } from 'react-bootstrap'
import homepage from '../styles/homepage.module.scss'
import NavbarHomepage from '../component/NavbarHomePage'
import CButton from '../component/CButton'
import {AiOutlinePhone} from 'react-icons/ai'
import {BiLockAlt,} from 'react-icons/bi'
import {BsDownload} from 'react-icons/bs'
// import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className={homepage.header}> 
          <NavbarHomepage/>
          <Container>
              <div className='d-flex flex-column justify-content-center align-items-center'>
                <h1 className={`${homepage.titleHeader} text-center fw-bolder text-white`}>Awesome App For Saving Time.</h1>
            </div>
              <div className={`mt-5 text-center fs-4 ${homepage.textHeader} text-white`}>
              We bring you a mobile app for banking problems that oftenly wasting much of your times.
            </div>
            <div className='mt-5 text-center'>
              <CButton className={homepage.button}>Try It Free</CButton>
            </div>
          </Container>
      </header>
      <section>
        <Container>
        <h1 className={`text-center mt-5 ${homepage.title} fw-bolder text-primary`}>Why Choose On-Wallet?</h1>
          <div className={`text-center mt-5 text-primary fs-5`}>We have some great features from the application and it’s totally free to use by all users around the world.</div>
          <Row className='mt-5 mb-5'>
            <Col>
              <div className='d-flex flex-column justify-content-center align-items-center text-center'>
                <div className={`${homepage.icon} text-center`}><AiOutlinePhone/></div>
                  <h4 className='text-primary mt-4 fs-4 fw-bold'>24/7 Support</h4>
                  <p className='text-primary mt-4 fs-5'>We have 24/7 contact support so you can contact us whenever you want and we will respond it.</p>
              </div>
            </Col>
            <Col>
              <div className={'d-flex flex-column justify-content-center align-items-center text-center'}>
                <div className={`${homepage.icon}`}><BiLockAlt/></div>
                <h4 className='text-primary mt-4 fs-4 fw-bold'>Data Privacy</h4>
                <p className='text-primary mt-4 fs-5'>We make sure your data is safe in our database and we will encrypt any data you submitted to us.</p>
              </div>
            </Col>
            <Col>
                <div className='d-flex flex-column justify-content-center align-items-center text-center'>
                  <div className={`${homepage.icon}`}><BsDownload/></div>
                  <h4 className='text-primary mt-4 fs-4 fw-bold'>Easy Download</h4>
                  <p className='text-primary mt-4 fs-5'>On-wallet is 100% totally free to use it’s now available on Google Play Store and App Store.</p>
                </div>
            </Col>
          </Row>
        </Container>
      </section>
      <section className={homepage.sectionAboutWallet}>
          <Container>
              <Row>
                <Col xs="4" md="3" lg="2">
                  <Image src="/images/microsoft.png" width={300} height={200} alt="microsoft" className='align-items-center'/>
                </Col>
                <Col xs="4" md="3" lg="2">
                  <Image src="/images/dropbox.png" width={300} height={200} alt="dropbox"/>
                </Col>
                <Col xs="4" md="3" lg="2">
                  <Image src="/images/h&m.png" width={300} height={200} alt="h&m"/>
                </Col>
                <Col xs="4" md="3" lg="2">
                  <Image src="/images/air-bnb.png" width={300} height={200} alt="air-bnb"/>
                </Col>
                <Col xs="4" md="3" lg="2">
                  <Image src="/images/canon.png" width={300} height={200} alt="canon"/>
                </Col>
                <Col xs="4" md="3" lg="2">
                  <Image src="/images/dell.png" width={300} height={200} alt="dell"/>
                </Col>
              </Row>
          </Container>
      </section>
      <section className='mb-5'>
        <Container>
          <div className='d-flex flex-column justify-content-center align-items-center text-center'>
            <p className={`${homepage.balance} mt-5 text-primary d-flex justify-content-center align-items-center text-center`}>Rp. 390.736.500</p>
          </div>
          <h1 className={`${homepage.description} text-primary text-center mt-4`}>Money has Been Transfered.</h1>
          <p className='text-center fs-4 text-primary mt-3'>That amount of money has been transfered from all users. We still counting and going strong!</p>        
        </Container>
      </section>
      <section className={homepage.sectionFeatureWallet}>
        <Container>
          <div className='mb-4'>
          <Row>
              <Col md={5}>
                <div clssName="position-relative">
                  {/* <Image src="/images/png-phone2.png" className='msposition-absolute' width={300} height={400} alt="phone1"/>
                  <Image src="/images/png-phone.png" className='ms-0position-absolute' width={300} height={400} alt="phone1"/> */}
                </div>
              </Col>
              <Col md={7}>
                <h1 className={`${homepage.description} mt-5 fw-bold text-primary`}>All The Great Zwallet Features</h1>
                <div className={`${homepage.detailFeature} mt-3 ps-3 pt-2`}>
                  <div className='fs-4 text-primary fw-bold'>1. Small Fee</div>
                  <div className='fs-6 text-primary mt-2'>We only charge 5% of every success transaction done in Zwallet app.</div>
                </div>
                <div className={`${homepage.detailFeature} mt-3 ps-3 pt-2`}>
                  <div className='fs-4 text-primary fw-bold'>2. Data Secured</div>
                  <div className='fs-6 text-primary mt-2'>All your data is secured properly in our system and it’s encrypted.</div>
                </div>
                <div className={`${homepage.detailFeature} mt-3 ps-3 pt-2 mb-5`}>
                  <div className='fs-4 text-primary fw-bold'>3. User Friendly</div>
                  <div className='fs-6 text-primary mt-2 mb-3'>Zwallet come up with modern and sleek design and not complicated..</div>
                </div>
              </Col>
            </Row>  
          </div>      
        </Container>
      </section>
    </>
    // <div className={styles.container}>
    //   <Head>
    //     <title>Create Next App</title>
    //     <meta name="description" content="Generated by create next app" />
    //     <link rel="icon" href="/favicon.ico" />
    //   </Head>

    //   <main className={styles.main}>
    //     <h1 className={styles.title}>
    //       Welcome to <a href="https://nextjs.org">Next.js!</a>
    //     </h1>

    //     <p className={styles.description}>
    //       Get started by editing{' '}
    //       <code className={styles.code}>pages/index.js</code>
    //     </p>

    //     <div className={styles.grid}>
    //       <a href="https://nextjs.org/docs" className={styles.card}>
    //         <h2>Documentation &rarr;</h2>
    //         <p>Find in-depth information about Next.js features and API.</p>
    //       </a>

    //       <a href="https://nextjs.org/learn" className={styles.card}>
    //         <h2>Learn &rarr;</h2>
    //         <p>Learn about Next.js in an interactive course with quizzes!</p>
    //       </a>

    //       <a
    //         href="https://github.com/vercel/next.js/tree/canary/examples"
    //         className={styles.card}
    //       >
    //         <h2>Examples &rarr;</h2>
    //         <p>Discover and deploy boilerplate example Next.js projects.</p>
    //       </a>

    //       <a
    //         href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
    //         className={styles.card}
    //       >
    //         <h2>Deploy &rarr;</h2>
    //         <p>
    //           Instantly deploy your Next.js site to a public URL with Vercel.
    //         </p>
    //       </a>
    //     </div>
    //   </main>

    //   <footer className={styles.footer}>
    //     <a
    //       href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
    //       target="_blank"
    //       rel="noopener noreferrer"
    //     >
    //       Powered by{' '}
    //       <span className={styles.logo}>
    //         <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
    //       </span>
    //     </a>
    //   </footer>
    // </div>
  )
}
